CREATE TABLE dbo.OrderDetailAudit
(
	ID INT NOT NULL IDENTITY(1, 1),
	OrderID INT NOT NULL,
	LineID INT NOT NULL,
	ClusterID INT NOT NULL,
	ProductCode VARCHAR(200),
	MachineID INT NOT NULL,
	Quantity INT NOT NULL,
	[Date] DATE NULL,
	CreatedUser INT NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedUser INT NOT NULL,
	UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_OrderDetailAudit PRIMARY KEY CLUSTERED (ID)
);