CREATE TABLE dbo.OrderDetail 
(
	ID INT NOT NULL IDENTITY(1, 1),
	OrderID INT NOT NULL,
	ProductCode VARCHAR(200),
	LineID INT NOT NULL,
	ClusterID INT NOT NULL,
	StaticShiftID INT NOT NULL,
	FixedStartTime VARCHAR(10) NULL,
	FixedEndTime VARCHAR(10) NULL,
	TargetQuantity INT NOT NULL DEFAULT(0),
	CreatedUser INT NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedUser INT NOT NULL,
	UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_OrderDetail PRIMARY KEY CLUSTERED (ID)
);