CREATE TABLE dbo.Cluster 
(
	ClusterID INT NOT NULL IDENTITY(1, 1),
	ClusterName NVARCHAR(200) NOT NULL,
	CreatedUser INT NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedUser INT NOT NULL,
	UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_Cluster PRIMARY KEY CLUSTERED (ClusterID)
);