CREATE TABLE dbo.Machine 
(
	MachineID INT NOT NULL IDENTITY(1, 1),
	MachineName NVARCHAR(200) NOT NULL,
	ClusterID INT,
	IsSum BIT DEFAULT(0),
	CreatedUser INT NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedUser INT NOT NULL,
	UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_Machine PRIMARY KEY CLUSTERED (MachineID)
);
