CREATE TABLE dbo.Product 
(
	ProductID INT NOT NULL IDENTITY(1, 1),
	ProductCode VARCHAR(200) NOT NULL,
	Productname VARCHAR(200) NOT NULL,
	CreatedUser INT NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedUser INT NOT NULL,
	UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_Product PRIMARY KEY CLUSTERED (ProductID)
);