CREATE TABLE dbo.Line 
(
	LineID INT NOT NULL IDENTITY(1, 1),
	LineName NVARCHAR(200) NOT NULL,
	CreatedUser INT NOT NULL,
	CreatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	UpdatedUser INT NOT NULL,
	UpdatedDate DATETIME NOT NULL DEFAULT(GETDATE()),
	IsDeleted BIT NOT NULL DEFAULT(0),
	CONSTRAINT PK_Line PRIMARY KEY CLUSTERED (LineID)
);